bb:
    extends:
        file: base.yml
        service: bb
    links:
        - bbdb:postgres
    image: docker.ternaris.com/bagbunker/bagbunker:staging
    volumes:
        - ../..:/home/bagbunker/code/bagbunker

bbdb:
    extends:
        file: base.yml
        service: bbdb
    image: docker.ternaris.com/bagbunker/postgres:staging
