bb:
    extends:
        file: base.yml
        service: bb
    image: docker.ternaris.com/bagbunker-develop/bagbunker
    ports:
        - ${BB_DEV_LISTEN}:5000
    volumes:
        - ../..:/home/bagbunker/code/bagbunker
    links:
        - bbdb:postgres
    environment:
        BB_DEV_LISTEN:

bbdb:
    extends:
        file: base.yml
        service: bbdb
